### ISSUE TITLE
Demo not working in test environment , Why do I keep getting connection timeout?

### ISSUE THREAD

**Issue by jigarmurabiya** [TransbankDevelopers/transbank-sdk-php-webpay-example#5]
hello team ,

i have setup this demo on my server but i can not successfully run this demo with testing environment can you please help me to find issue 

Why do I keep getting connection timeout?
=> after submit token and redirect url getting connection timeout

please find below attachment for more information 

![Screenshot from 2020-01-31 12-05-55](https://user-images.githubusercontent.com/18063943/73518022-37447980-4423-11ea-83a3-d7d00980fd1d.png)
![Screenshot from 2020-01-31 12-13-55](https://user-images.githubusercontent.com/18063943/73518041-43303b80-4423-11ea-8768-5161319cb406.png)

let me know there is something missing in integration or step to run demo in test mode or primary requirement for running this demo

Thank you!!!

**Comment by saengate** [comment]
@jigarmurabiya Hello, first of all, sorry if my English has flaws. I have done tests and the example does not seem to have errors. Can you tell me step by step how you did the installation and the test to try to replicate the problem you are presenting?

**Comment by saengate** [comment]
@jigarmurabiya it is likely that your ip is blocked. You can communicate internally to see what solutions we can find for this.
write me here to Saul Galan or Gonzalo De Spirito https://join-transbankdevelopers-slack.herokuapp.com/

**Comment by jigarmurabiya** [comment]
Solved Thank you!!
